// Fletching
mods.jei.JEI.hide(<tconstruct:fletching>.withTag({Material: "steeleaf"}));
mods.jei.JEI.hide(<tconstruct:fletching>.withTag({Material: "raven_feather"}));
mods.jei.JEI.hide(<tconstruct:fletching>.withTag({Material: "feather"}));
mods.jei.JEI.hide(<tconstruct:fletching>.withTag({Material: "slimeleaf_blue"}));
mods.jei.JEI.hide(<tconstruct:fletching>.withTag({Material: "slimeleaf_orange"}));
mods.jei.JEI.hide(<tconstruct:fletching>.withTag({Material: "slimeleaf_purple"}));
mods.jei.JEI.hide(<tconstruct:fletching>.withTag({Material: "leaf"}));
mods.jei.JEI.hide(<tconstruct:fletching>.withTag({Material: "stymph_feather"}));
mods.jei.JEI.hide(<tconstruct:fletching>.withTag({Material: "amphithere_feather"}));